import React, { useState } from "react";
import { ActivityIndicator, Alert, Image, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import { LinearGradient } from "expo-linear-gradient";
import { AuraLogoText } from "../components/AuraLogoText";
import { useAuth } from "../context/AuthContext";
import { useTheme } from "../context/ThemeContext";

const genders = ["여성", "남성", "논바이너리", "응답하지 않음"];
const orientations = ["이성애", "동성애", "양성애", "범성애", "무성애", "응답하지 않음"];
const ages = Array.from({ length: 83 }, (_, i) => String(i + 18));

export const RegisterScreen = ({ navigation }: any) => {
  const [form, setForm] = useState({ username: "", email: "", fullName: "", password: "", age: "", gender: "", orientation: "", height: "", bodyType: "", bio: "" });
  const [code, setCode] = useState(""); const [sentCode, setSentCode] = useState(""); const [verified, setVerified] = useState(false); const [picker, setPicker] = useState<keyof typeof form | null>(null); const [image, setImage] = useState<string | undefined>(); const [loading, setLoading] = useState(false);
  const { register } = useAuth(); const { colors } = useTheme();
  const set = (key: keyof typeof form, value: string) => setForm(f => ({ ...f, [key]: value }));
  const input = (key: keyof typeof form, placeholder: string, extra: any = {}) => <TextInput style={[styles.input, { backgroundColor: colors.bgInput, borderColor: colors.borderColor, color: colors.textPrimary }]} placeholder={placeholder} placeholderTextColor={colors.textSecondary} value={form[key]} onChangeText={v => set(key, v)} {...extra} />;
  const chooseImage = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: true, aspect: [1, 1], quality: .8 }); if (!result.canceled) setImage(result.assets[0].uri); };
  const sendCode = () => { if (!form.email.trim()) return Alert.alert("입력 확인", "이메일 주소를 먼저 입력해주세요."); setSentCode("123456"); Alert.alert("인증번호 발송", "인증번호가 발송되었습니다."); };
  const verifyCode = () => { if (code === sentCode && sentCode) setVerified(true); else Alert.alert("인증 실패", "인증번호를 확인해주세요."); };
  const submit = async () => { if (!form.fullName || !form.age || !form.email || !verified || !form.gender || !form.orientation || !form.username || !form.password) return Alert.alert("필수 항목 확인", "필수 항목을 모두 입력하고 이메일 인증을 완료해주세요."); setLoading(true); try { await register({ username: form.username.trim(), email: form.email.trim().toLowerCase(), full_name: form.fullName.trim(), password: form.password, age: Number(form.age), gender: form.gender, sexual_orientation: form.orientation, height: form.height || undefined, body_type: form.bodyType || undefined, bio: form.bio || undefined, profile_image_url: image }); } catch (e: any) { Alert.alert("회원가입 실패", e.response?.data?.detail || e.message || "회원가입에 실패했습니다."); } finally { setLoading(false); } };
  const options = picker === "age" ? ages : picker === "gender" ? genders : orientations;
  return <SafeAreaView style={[styles.container, { backgroundColor: colors.bgPrimary }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><AuraLogoText fontSize={40} /><Text style={[styles.subtitle, { color: colors.textSecondary }]}>새 계정 만들기</Text>
    {input("fullName", "이름 *")}{input("username", "닉네임 *", { autoCapitalize: "none" })}
    <View style={styles.row}><TouchableOpacity style={[styles.select, { backgroundColor: colors.bgInput, borderColor: colors.borderColor }]} onPress={() => setPicker("age")}><Text style={{ color: form.age ? colors.textPrimary : colors.textSecondary }}>{form.age ? `${form.age}세` : "나이 *"}</Text></TouchableOpacity><TouchableOpacity style={[styles.select, { backgroundColor: colors.bgInput, borderColor: colors.borderColor }]} onPress={() => setPicker("gender")}><Text style={{ color: form.gender ? colors.textPrimary : colors.textSecondary }}>{form.gender || "성별 *"}</Text></TouchableOpacity></View>
    <View style={styles.emailRow}>{input("email", "이메일 주소 *", { keyboardType: "email-address", autoCapitalize: "none" })}<TouchableOpacity style={styles.smallButton} onPress={sendCode}><Text style={styles.smallText}>인증번호</Text></TouchableOpacity></View><View style={styles.emailRow}>{input("password", "비밀번호 *", { secureTextEntry: true })}{sentCode && <TouchableOpacity style={[styles.smallButton, verified && styles.verified]} onPress={verifyCode}><Text style={styles.smallText}>{verified ? "인증 완료" : "확인"}</Text></TouchableOpacity>}</View>{sentCode && input("bio" as any, "인증번호 6자리", { value: code, onChangeText: setCode, keyboardType: "number-pad", maxLength: 6 })}
    <TouchableOpacity style={[styles.selectFull, { backgroundColor: colors.bgInput, borderColor: colors.borderColor }]} onPress={() => setPicker("orientation")}><Text style={{ color: form.orientation ? colors.textPrimary : colors.textSecondary }}>{form.orientation || "성적 지향 *"}</Text></TouchableOpacity>
    <Text style={[styles.section, { color: colors.textPrimary }]}>선택 입력</Text>{input("height", "키 (cm)", { keyboardType: "numeric" })}{input("bodyType", "체형")}{input("bio", "자기소개", { multiline: true, numberOfLines: 3 })}
    <TouchableOpacity style={styles.photo} onPress={chooseImage}>{image ? <Image source={{ uri: image }} style={styles.avatar} /> : <Text style={{ color: colors.textSecondary }}>프로필 사진 등록</Text>}</TouchableOpacity>
    <TouchableOpacity onPress={submit} disabled={loading}><LinearGradient colors={(colors.auraGradient || ["#8b5cf6", "#ec4899", "#06b6d4"]) as [string, string, ...string[]]} style={styles.button}><Text style={styles.buttonText}>{loading ? <ActivityIndicator color="#fff" /> : "회원가입"}</Text></LinearGradient></TouchableOpacity><View style={styles.footer}><Text style={{ color: colors.textSecondary }}>이미 계정이 있나요? </Text><TouchableOpacity onPress={() => navigation.navigate("Login")}><Text style={styles.link}>로그인</Text></TouchableOpacity></View>
  </ScrollView><Modal transparent visible={!!picker} animationType="fade"><Pressable style={styles.modal} onPress={() => setPicker(null)}><View style={[styles.options, { backgroundColor: colors.bgSecondary }]}>{options.map(o => <TouchableOpacity key={o} style={styles.option} onPress={() => { set(picker!, o); setPicker(null); }}><Text style={{ color: colors.textPrimary }}>{picker === "age" ? `${o}세` : o}</Text></TouchableOpacity>)}</View></Pressable></Modal></SafeAreaView>;
};
const styles = StyleSheet.create({ container:{flex:1},content:{padding:24,paddingBottom:40},subtitle:{textAlign:"center",marginVertical:10},input:{flex:1,borderWidth:1,borderRadius:10,padding:14,fontSize:15,marginBottom:10},row:{flexDirection:"row",gap:10},select:{flex:1,borderWidth:1,borderRadius:10,padding:14,marginBottom:10},selectFull:{borderWidth:1,borderRadius:10,padding:14,marginBottom:10},emailRow:{flexDirection:"row",gap:8},smallButton:{height:48,paddingHorizontal:12,borderRadius:10,backgroundColor:"#8b5cf6",justifyContent:"center",marginBottom:10},smallText:{color:"#fff",fontWeight:"700"},verified:{backgroundColor:"#16a34a"},section:{fontWeight:"700",marginVertical:8},photo:{height:110,borderWidth:1,borderColor:"#555",borderRadius:12,borderStyle:"dashed",alignItems:"center",justifyContent:"center",marginBottom:14},avatar:{width:90,height:90,borderRadius:45},button:{padding:15,borderRadius:10,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"700",fontSize:16},footer:{flexDirection:"row",justifyContent:"center",marginTop:24},link:{color:"#8b5cf6",fontWeight:"700"},modal:{flex:1,backgroundColor:"#0008",justifyContent:"center",padding:30},options:{borderRadius:14,maxHeight:420},option:{padding:16,borderBottomWidth:1,borderBottomColor:"#ffffff18"}});
